version: '3.8'

services:
  trading-server:
    build: ./server
    ports:
      - "3001:3001"
      - "8080:8080"
    environment:
      ALPACA_KEY: ${ALPACA_KEY}
      ALPACA_SECRET: ${ALPACA_SECRET}
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - redis
      - ml-service

  ml-service:
    build: ./ml-service
    ports:
      - "5001:5001"
    environment:
      MODEL_PATH: "/models"

  redis:
    image: "redis/redis-stack-server:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - trading-server

volumes:
  redis-data:
